# copied from https://github.com/Sabolik/nixie-clock-hw/blob/main/.github/workflows/kibot_fab.yml

name: KiBot CI

on:
  push:
    paths:
    - '**.kicad_sch'
    - '**.kicad_pcb'

  workflow_dispatch:

jobs:
  erc:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:1.8.4-3_k9.0.1_d12.7_b4.2.4LTS

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Run ERC
      run: |
        kibot -e RadioHAT.kicad_sch -b RadioHAT.kicad_pcb -d generated -s run_drc -i
        kibot -e RadioHAT_Card_Dorji/RadioHAT_Card_Dorji.kicad_sch -b RadioHAT_Card_Dorji/RadioHAT_Card_Dorji.kicad_pcb -d generated -s run_drc -i
        kibot -e RadioHAT_Card_GNiceRF/RadioHAT_Card_GNiceRF.kicad_sch -b RadioHAT_Card_GNiceRF/RadioHAT_Card_GNiceRF.kicad_pcb -d generated -s run_drc -i

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC_Output
        path: generated

  drc:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:1.8.4-3_k9.0.1_d12.7_b4.2.4LTS
    needs: erc

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Run DRC
      run: |
        kibot -e RadioHAT.kicad_sch -b RadioHAT.kicad_pcb -d generated -s run_erc -i
        kibot -e RadioHAT_Card_Dorji/RadioHAT_Card_Dorji.kicad_sch -b RadioHAT_Card_Dorji/RadioHAT_Card_Dorji.kicad_pcb -d generated -s run_erc -i
        kibot -e RadioHAT_Card_GNiceRF/RadioHAT_Card_GNiceRF.kicad_sch -b RadioHAT_Card_GNiceRF/RadioHAT_Card_GNiceRF.kicad_pcb -d generated -s run_erc -i

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: DRC_Output
        path: generated

  fab:
    name: generate fabrication files
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    container: ghcr.io/inti-cmnb/kicad9_auto_full:1.8.4-3_k9.0.1_d12.7_b4.2.4LTS
    needs: drc

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Generate fab data
      run: |
        kibot -e RadioHAT.kicad_sch -b RadioHAT.kicad_pcb -d generated 3d-render-view pcb_doc_archive pcb_assembly_archive pcb_fabrication_archive
        kibot -e RadioHAT_Card_Dorji/RadioHAT_Card_Dorji.kicad_sch -b RadioHAT_Card_Dorji/RadioHAT_Card_Dorji.kicad_pcb -d generated 3d-render-view pcb_doc_archive pcb_assembly_archive pcb_fabrication_archive
        kibot -e RadioHAT_Card_GNiceRF/RadioHAT_Card_GNiceRF.kicad_sch -b RadioHAT_Card_GNiceRF/RadioHAT_Card_GNiceRF.kicad_pcb -d generated 3d-render-view pcb_doc_archive pcb_assembly_archive pcb_fabrication_archive

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: generated/*